server:
  port: 8011
spring:
  application:
    name: openfeign-okhttp
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
# 日志
logging:
  level:
    com.msr.better.feign.service.HelloFeignService: debug